#!/usr/bin/env bash
# Bash script similar to 7-highlander.

trap "echo Y U no love me?!"  SIGINT
trap imdead SIGQUIT SIGTERM

echo "$$" > "/var/run/myscript.pid"
while true
do
	echo "To infinity and beyond"
	sleep 2
done
function imdead() {
	echo "I hate the kill command"
	rm -f "/var/run/myscript.pid"
	exit 1
}
