#!/usr/bin/env bash
# Bash script similar to 7-highlander but using more signals and optionaly functions.

trap "echo Y U no love me?!"  SIGINT
trap imdead SIGQUIT SIGTERM

function imdead()
{
	echo "I hate the kill command"
	rm -f "/var/run/myscript.pid"
	exit 1
}

echo "$$" > "/var/run/myscript.pid"
while true
do
	echo "To infinity and beyond"
	sleep 2
done
