#!/usr/bin/env bash
# Fizz Buzz in bash using lists

list=()

for number in {1..100}
do
	if [[ $((number%3)) == 0 ]] && [[ $((number%5)) == 0 ]]
	then
		list=("${list[@]}" "FizzBuzz")
	elif [ $((number%3)) == 0 ]
	then
		list=("${list[@]}" "Fizz")
	elif [ $((number%5)) == 0 ]
	then
		list=("${list[@]}" "Buzz")
	else
		list=("${list[@]}" "$number")
	fi
done

for value in "${list[@]}"
do
     echo "$value"
done
