#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while

count=1
while [ $count -le 10 ]
do
	if [ $count -ne 9 ];
	then
		echo "Best School"
	else
		echo "Hi"
	fi
  count=$((count + 1))
done
