#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while and if

count=1
while [ $count -le 10 ] && [ $count -gt 0 ]
do
	if [ $count -eq 9 ];
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
