#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while and case

count=1
while [ $count -le 10 ]
do
	case $count in
		4)	echo "bad luck";;
		8)	echo "good luck";;
		*)	echo "Best School";;
	esac
	count=$((count + 1))
done
