#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using while and case

count=1
while [ $count -le 10 ]
do
	echo "$count"
	case $count in
		4)	echo "bad luck from China";;
		9)	echo "bad luck from Japan";;
		17)	echo "bad luck from Italy";;
		*)	;;
	esac
	count=$((count + 1))
done
