#!/usr/bin/env bash
# Display every minute and hour from 00:01 to 12:59

hour=0
while [ $hour -le 12 ]
do
	minute=1
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$((minute + 1))
	done
	hour=$((hour + 1))
done
