#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ifconfig | grep -o -E '^ +inet [[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}.[[:digit:]]{1,3}' | awk '{print $2}'
